const ids=['from','to','date','klass','mode','seats','count','enabled'];
const defaults={from:'Dhaka',to:"Cox's Bazar",date:'',klass:'AC_B',train:'',mode:'named',seats:'GHA-11, GHA-13',count:1,enabled:true};
const status=document.querySelector('#status'); const trainSelect=document.querySelector('#train'); const trainText=document.querySelector('#trainText');
chrome.storage.sync.get(defaults,s=>{ids.forEach(id=>{const e=document.querySelector('#'+id); if(e.type==='checkbox')e.checked=s[id]; else e.value=s[id]||'';});trainText.value=s.train||'';});
function values(){const o={};ids.forEach(id=>{const e=document.querySelector('#'+id);o[id]=e.type==='checkbox'?e.checked:e.value.trim();});o.train=(trainSelect.value||trainText.value||'').trim();o.seats=o.seats.split(/[,\s]+/).map(x=>x.trim().toUpperCase()).filter(Boolean).join(', ');return o;}
document.querySelector('#loadTrains').onclick=async()=>{const s=values();if(!s.from||!s.to||!s.date){status.textContent='From, To ও date দিন';return;}const p=s.date.split('-'),m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],date=p[2]+'-'+m[Number(p[1])-1]+'-'+p[0];const url='https://railspaapi.shohoz.com/v1.0/web/bookings/search-trips-v2?from_city='+encodeURIComponent(s.from)+'&to_city='+encodeURIComponent(s.to)+'&date_of_journey='+encodeURIComponent(date)+'&seat_class='+encodeURIComponent(s.klass);status.textContent='Shohoz page-এর API থেকে train লোড হচ্ছে…';chrome.tabs.query({active:true,currentWindow:true},tabs=>{const tab=tabs[0];if(!tab?.id||!String(tab.url||'').startsWith('https://train.shohoz.com/')){status.textContent='আগে Shohoz tab খুলুন';return;}chrome.tabs.sendMessage(tab.id,{type:'SHOHOZ_LOAD_TRAINS',url},response=>{if(chrome.runtime.lastError||!response?.ok){status.textContent='Shohoz tab reload করে আবার চেষ্টা করুন';return;}const list=response.data?.data?.trains||[];trainSelect.innerHTML='<option value="">ট্রেন বেছে নিন</option>';list.forEach(t=>{const o=document.createElement('option');o.value=t.trip_number;o.textContent=t.trip_number+' — '+t.departure_date_time;trainSelect.appendChild(o);});status.textContent=list.length+'টি ট্রেন পাওয়া গেছে';});});};
document.querySelector('#run').onclick=()=>{const s=values();if(!s.from||!s.to||!s.date||!s.train||!s.seats){status.textContent='From, To, date, train ও seat পূরণ করুন';return;}chrome.storage.sync.set({...s,running:true},()=>{status.textContent='Automation started';const parts=s.date.split('-');const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];const date=parts.length===3?parts[2]+'-'+months[Number(parts[1])-1]+'-'+parts[0]:s.date;const u='https://train.shohoz.com/booking/train/search?fromcity='+encodeURIComponent(s.from)+'&tocity='+encodeURIComponent(s.to)+'&doj='+encodeURIComponent(date)+'&class='+encodeURIComponent(s.klass);chrome.tabs.create({url:u});});};
document.querySelector('#stop').onclick=()=>chrome.storage.sync.set({running:false},()=>status.textContent='Stopped');

trainSelect.addEventListener('change',()=>{if(trainSelect.value)trainText.value='';});
